#BOW(Bag of words)

In [ ]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

In [ ]:
import re
import nltk


nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords

from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
# Cleaning the texts

stemmer = PorterStemmer()

lemitizer=WordNetLemmatizer()

sentences = nltk.sent_tokenize(paragraph) #split the paragraph to individual sentences based on spaces.

corpus = []

for i in range(len(sentences)): ##loop for each sentences individually

    review = re.sub('[^a-zA-Z]', ' ', sentences[i]) #replace any thing othwerwise characters with space
    review = review.lower()
    review = review.split()
    #review = [stemmer.stem(word) for word in review if not word in set(stopwords.words('english'))] #bad result
    review = [lemitizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
print(len(corpus))
corpus

31


['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked

In [ ]:
# # Creating the Bag of Words model
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer()
# x = cv.fit_transform(corpus)
# x

# #but x is still in sparse matrix shape

<31x114 sparse matrix of type '<class 'numpy.int64'>'
	with 155 stored elements in Compressed Sparse Row format>

In [ ]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
print(x.shape)
x
#so we have 114 unique words

(31, 114)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#N-GRAM

##UNi-GRAM

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

# give each word individually and it's index as a column
# by default(one gram)
# using fit function not fit_transform

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

In [ ]:
v = CountVectorizer(ngram_range=(1,1))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

##BI-GRAM

In [ ]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 9,
 'hathodawala': 2,
 'is': 4,
 'looking': 7,
 'for': 0,
 'job': 6,
 'thor hathodawala': 10,
 'hathodawala is': 3,
 'is looking': 5,
 'looking for': 8,
 'for job': 1}

In [ ]:
v = CountVectorizer(ngram_range=(1,3))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 12,
 'hathodawala': 2,
 'is': 5,
 'looking': 9,
 'for': 0,
 'job': 8,
 'thor hathodawala': 13,
 'hathodawala is': 3,
 'is looking': 6,
 'looking for': 10,
 'for job': 1,
 'thor hathodawala is': 14,
 'hathodawala is looking': 4,
 'is looking for': 7,
 'looking for job': 11}

##Task :

1- remove stop words

2- lemmatize the text

3- apply n-gram

In [ ]:
corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

In [ ]:
import spacy

# load english language model
nlp = spacy.load("en_core_web_sm")

def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)

    return " ".join(filtered_tokens)

In [ ]:
preprocess("Thor ate pizza")


'thor eat pizza'

In [ ]:
preprocess("Loki is eating pizza")


'Loki eat pizza'

In [ ]:
corpus_processed = [
    preprocess(text) for text in corpus
]
corpus_processed

['thor eat pizza', 'Loki tall', 'Loki eat pizza']

In [ ]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(corpus_processed)
v.vocabulary_

{'thor': 7,
 'eat': 0,
 'pizza': 5,
 'thor eat': 8,
 'eat pizza': 1,
 'loki': 2,
 'tall': 6,
 'loki tall': 4,
 'loki eat': 3}

In [ ]:
# fit >>>> take all the documents.
# transform  >>> take sentence that you want to encode it.
v.transform(["Thor eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 1, 1]])

In [ ]:
v.transform(["Hulk eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 0, 0]])

#TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [ ]:
# Example documents
docs = [
  "The quick brown fox jumps over the lazy dog.",
  "A stitch in time saves nine.",
  "The early bird catches the worm.",
  "Actions speak louder than words.",
]

In [ ]:
# Create a TF-IDF vectorizer instance
tfidf = TfidfVectorizer()

# Fit the vectorizer to the documents
tfidf.fit(docs)

# Transform the documents into a TF-IDF matrix
tfidf_matrix = tfidf.transform(docs)
print(tfidf_matrix.toarray())

# YOU CAN MAKE IT IN ONE LINE using fit_transform.

[[0.         0.         0.32467583 0.         0.32467583 0.
  0.32467583 0.         0.32467583 0.32467583 0.         0.
  0.32467583 0.32467583 0.         0.         0.         0.
  0.5119563  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.4472136  0.         0.         0.         0.4472136
  0.         0.         0.4472136  0.         0.4472136  0.
  0.         0.4472136  0.         0.        ]
 [0.         0.39264414 0.         0.39264414 0.         0.39264414
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.6191303  0.         0.         0.39264414]
 [0.4472136  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.4472136  0.
  0.         0.         0.         0.4472136  0.         0.4472136
  0.         0.         0.4472136  0.        ]]


When sklearn.__version__ <= 0.24.x use following method

get_feature_names()


When sklearn.__version__ >= 1.0.x use following method

get_feature_names_out()

In [ ]:
# Convert the matrix to a pandas dataframe
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

# Display the dataframe
print(df_tfidf)


# will make every unique word as a feature, so because i have 22 columns.
# noticed, the most frequency word is the least value of TF-IDF

    actions      bird     brown   catches       dog     early       fox  \
0  0.000000  0.000000  0.324676  0.000000  0.324676  0.000000  0.324676   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.392644  0.000000  0.392644  0.000000  0.392644  0.000000   
3  0.447214  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         in     jumps      lazy  ...      over     quick     saves     speak  \
0  0.000000  0.324676  0.324676  ...  0.324676  0.324676  0.000000  0.000000   
1  0.447214  0.000000  0.000000  ...  0.000000  0.000000  0.447214  0.000000   
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.447214   

     stitch      than       the      time     words      worm  
0  0.000000  0.000000  0.511956  0.000000  0.000000  0.000000  
1  0.447214  0.000000  0.000000  0.447214  0.000000  0.000000  
2  0.000000  0.000000  0.619130

## the numbers of uniques words(min_df)

1- min_df>>>>>>> will control the numbers of words which will be appeared based on numbers of frequency

In [ ]:
#the default of min_df is one
doc1 = "the quick brown fox"
doc2 = "the lazy dog"
doc3 = "the quick brown cat"

cv = TfidfVectorizer()
X = cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())  # ['brown', 'cat', 'dog', 'fox', 'lazy', 'quick', 'the']
print(X.toarray())

['brown' 'cat' 'dog' 'fox' 'lazy' 'quick' 'the']
[[0.4804584  0.         0.         0.63174505 0.         0.4804584
  0.37311881]
 [0.         0.         0.65249088 0.         0.65249088 0.
  0.38537163]
 [0.4804584  0.63174505 0.         0.         0.         0.4804584
  0.37311881]]


In [ ]:
cv = TfidfVectorizer(min_df=2)
X = cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())  # ['brown', 'quick', 'the']
print(X.toarray())

#noticed thatcat,dog,fox,lazy]>>>>>> not appeared becuse the numbers of repeats less than two

['brown' 'quick' 'the']
[[0.61980538 0.61980538 0.48133417]
 [0.         0.         1.        ]
 [0.61980538 0.61980538 0.48133417]]


In [ ]:
cv = TfidfVectorizer(min_df=2,stop_words='english')
X = cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())  # ['brown', 'quick', 'the']
print(X.toarray())

#noticed that [the]>>>>>>>>not appeared becuse it is from stop_word

['brown' 'quick']
[[0.70710678 0.70710678]
 [0.         0.        ]
 [0.70710678 0.70710678]]


##Another Example

In [ ]:
text=["Hi How are you How are you doing","Hi what's up","Wow that's awesome"]
cv = TfidfVectorizer(min_df=1)
x_traincv = cv.fit_transform(text)
feature_names = cv.get_feature_names_out()

# Print the feature names and the TF-IDF matrix
print(feature_names)
print(x_traincv.toarray())

['are' 'awesome' 'doing' 'hi' 'how' 'that' 'up' 'what' 'wow' 'you']
[[0.54275734 0.         0.27137867 0.20639047 0.54275734 0.
  0.         0.         0.         0.54275734]
 [0.         0.         0.         0.4736296  0.         0.
  0.62276601 0.62276601 0.         0.        ]
 [0.         0.57735027 0.         0.         0.         0.57735027
  0.         0.         0.57735027 0.        ]]


In [ ]:
#Another Example

text=["Hi How are you How are you doing","Hi what's up","Wow that's awesome"]
cv = TfidfVectorizer(min_df=1,stop_words='english')
x_traincv = cv.fit_transform(text)
feature_names = cv.get_feature_names_out()

# Print the feature names and the TF-IDF matrix
print(feature_names)
print(x_traincv.toarray())

['awesome' 'doing' 'hi' 'wow']
[[0.         0.79596054 0.60534851 0.        ]
 [0.         0.         1.         0.        ]
 [0.70710678 0.         0.         0.70710678]]


#Word Embedding

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sents=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sents

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

1-  In general, a larger vocabulary size allows for a more nuanced representation of the language, but it also increases the computational cost of training the embedding model. On the other hand, a smaller vocabulary size may limit the expressiveness of the embeddings and reduce the accuracy of the trained model.

2- A reasonable starting point for a vocabulary size is around 20,000 to 30,000, but this may need to be adjusted up or down depending on your specific use case. If you have a smaller dataset or are working with a less complex language, you may be able to use a smaller vocabulary size

In [ ]:
### Vocabulary size>>>> the size of unique words
voc_size=10000

#### One Hot Representation

In [ ]:
#will make one hot encoding and return each sentence with it's indices

onehot_repr=[one_hot(sent,voc_size)for sent in sents]
print(onehot_repr)


#[2725, 4751, 1322, 7778] >>>>>the glass of milk(the numbers of indices of the words)

[[2883, 7411, 3908, 6681], [2883, 7411, 3908, 6745], [2883, 8790, 3908, 8162], [3704, 3269, 5253, 4203, 8541], [3704, 3269, 5253, 4203, 6499], [5882, 2883, 1489, 3908, 6685], [6700, 2799, 5945, 4203]]


### Word Embedding Represntation

In [ ]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

1- here, we will pass the result of one hot to embedding layer.

2- but not all the sentences have same numbers of words , so i will make padding.

3- padding='pre' or 'post'>>>> the zeros before or after indices to be same size.

4- The choice of padding can affect the performance of the model, depending on the nature of the data. For example, if the end of the sequence is more important for the task at hand, you may want to use padding='pre' to preserve the order of the original sequence. On the other hand, if the beginning of the sequence is more important, you may want to use padding='post'. In some cases, it may be useful to try both options and see which one works better for your particular task.

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

# sent_length >>> maximum numbers of words in sentence

[[   0    0    0    0 2883 7411 3908 6681]
 [   0    0    0    0 2883 7411 3908 6745]
 [   0    0    0    0 2883 8790 3908 8162]
 [   0    0    0 3704 3269 5253 4203 8541]
 [   0    0    0 3704 3269 5253 4203 6499]
 [   0    0    0 5882 2883 1489 3908 6685]
 [   0    0    0    0 6700 2799 5945 4203]]


In [ ]:
dim=10
# dim >>> maximum numbers of vectors to represent one word in sentence.

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))
#there are the features would be used in the models

1/1 [==============================] - 0s 177ms/step
[[[-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563
    0.02848453 -0.04522064 -0.0022557  -0.01827334 -0.02757515]
  [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563
    0.02848453 -0.04522064 -0.0022557  -0.01827334 -0.02757515]
  [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563
    0.02848453 -0.04522064 -0.0022557  -0.01827334 -0.02757515]
  [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563
    0.02848453 -0.04522064 -0.0022557  -0.01827334 -0.02757515]
  [-0.00665476  0.00694273  0.02852154  0.04741776  0.01549859
   -0.03529092  0.03557928 -0.04992579 -0.00151428  0.03977767]
  [-0.02445742 -0.01039945  0.04892126  0.04749333 -0.01364492
   -0.02083243 -0.00756024  0.00465838  0.03740699 -0.0303151 ]
  [ 0.02832193  0.00847127  0.00370447 -0.03426734 -0.03310901
    0.00420745 -0.00620569  0.00268771 -0.04235294  0.03897474]
  [ 0.04649255  0.00369128 -0.01723834 -0.00226138  0.0013

In [ ]:
#frist sentence after onehot + padding
embedded_docs[0]

array([   0,    0,    0,    0, 2883, 7411, 3908, 6681], dtype=int32)

In [ ]:
#frist sentence after embedding
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 23ms/step
[[-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.00665476  0.00694273  0.02852154  0.04741776  0.01549859 -0.03529092
   0.03557928 -0.04992579 -0.00151428  0.03977767]
 [-0.02445742 -0.01039945  0.04892126  0.04749333 -0.01364492 -0.02083243
  -0.00756024  0.00465838  0.03740699 -0.0303151 ]
 [ 0.02832193  0.00847127  0.00370447 -0.03426734 -0.03310901  0.00420745
  -0.00620569  0.00268771 -0.04235294  0.03897474]
 [ 0.04649255  0.00369128 -0.01723834 -0.00226138  0.00130426  0.00321114

In [ ]:
print(model.predict(embedded_docs)[1])

1/1 [==============================] - 0s 33ms/step
[[-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.01999989  0.04437989  0.02153428 -0.025058    0.02389563  0.02848453
  -0.04522064 -0.0022557  -0.01827334 -0.02757515]
 [-0.00665476  0.00694273  0.02852154  0.04741776  0.01549859 -0.03529092
   0.03557928 -0.04992579 -0.00151428  0.03977767]
 [-0.02445742 -0.01039945  0.04892126  0.04749333 -0.01364492 -0.02083243
  -0.00756024  0.00465838  0.03740699 -0.0303151 ]
 [ 0.02832193  0.00847127  0.00370447 -0.03426734 -0.03310901  0.00420745
  -0.00620569  0.00268771 -0.04235294  0.03897474]
 [ 0.04068749 -0.02007303  0.02258701  0.02955471  0.04868075  0.03559405

In [ ]:
from gensim.models import Word2Vec
import nltk

# Tokenize the sentences into words
tokenized_sents = [nltk.word_tokenize(sent) for sent in sents]

# Create the Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_sents, vector_size=100, window=5, min_count=1, workers=4)

# Train the model
word2vec_model.train(tokenized_sents, total_examples=len(tokenized_sents), epochs=10)

# Get the vector for a specific word
word_vector = word2vec_model.wv['glass']
print(word_vector)